from django.core.management.base import BaseCommand
from webscraper.models import Dataset


class Command(BaseCommand):
    help = 'Populates the database with fake dataset entries for testing'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Delete all existing datasets before seeding',
        )

    def handle(self, *args, **options):
        if options['clear']:
            count = Dataset.objects.count()
            Dataset.objects.all().delete()
            self.stdout.write(
                self.style.WARNING(f'Deleted {count} existing datasets')
            )

        # Fake Datasets - Generated by Claude.ai
        fake_datasets = [
            {
                'title': 'Climate Change Data 2023',
                'description': 'Comprehensive climate data including temperature, precipitation, and CO2 levels from 1980-2023. Includes global and regional breakdowns.'
            },
            {
                'title': 'COVID-19 Global Statistics',
                'description': 'Daily updated COVID-19 case numbers, deaths, and vaccination rates across all countries. Includes demographic breakdowns and hospital capacity data.'
            },
            {
                'title': 'Stock Market Historical Prices',
                'description': 'Historical stock prices for S&P 500 companies from 2000-2024. Includes daily open, high, low, close, and volume data.'
            },
            {
                'title': 'World Population Demographics',
                'description': 'Population statistics by country, age group, and gender. Includes birth rates, death rates, and migration patterns from 1950-2024.'
            },
            {
                'title': 'Machine Learning Iris Dataset',
                'description': 'Classic iris flower dataset with 150 samples. Includes sepal length, sepal width, petal length, and petal width for three species.'
            },
            {
                'title': 'Air Quality Index USA Cities',
                'description': 'Daily air quality measurements for major US cities. Includes PM2.5, PM10, ozone, and other pollutant levels from 2010-2024.'
            },
            {
                'title': 'E-commerce Sales Transactions',
                'description': 'Anonymized e-commerce transaction data including product categories, prices, quantities, and customer demographics. 1 million transactions.'
            },
            {
                'title': 'Housing Prices California',
                'description': 'California housing market data with median house prices, number of rooms, population density, and geographic coordinates.'
            },
            {
                'title': 'Twitter Sentiment Analysis Dataset',
                'description': 'Collection of 1.6 million tweets labeled with sentiment (positive/negative). Useful for natural language processing and sentiment analysis.'
            },
            {
                'title': 'Global Energy Consumption',
                'description': 'Energy consumption by source (coal, oil, gas, nuclear, renewables) for all countries from 1965-2023. Includes per capita consumption.'
            },
            {
                'title': 'Medical Diagnosis Records',
                'description': 'Anonymized patient records with symptoms, test results, and diagnoses. Includes data for heart disease, diabetes, and cancer detection.'
            },
            {
                'title': 'Video Game Sales Data',
                'description': 'Sales figures for video games across different platforms and regions. Includes genre, publisher, and critic scores.'
            },
        ]

        datasets_to_create = []
        for data in fake_datasets:
            datasets_to_create.append(
                Dataset(
                    title=data['title'],
                    description=data['description']
                )
            )

        created = Dataset.objects.bulk_create(datasets_to_create)

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully created {len(created)} fake datasets!'
            )
        )
