# Generated by Django 5.2.8 on 2026-01-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0005_scrapingproject_userscrape_scrapeddataitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscrape',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userscrape',
            name='is_scheduled_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userscrape',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscrape',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscrape',
            name='schedule_frequency',
            field=models.CharField(choices=[('none', 'No Schedule'), ('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
    ]
